/*
BEGIN
    FOR SAYAC IN 1..5 LOOP
        CONTINUE WHEN SAYAC = 2;
        DBMS_OUTPUT.PUT_LINE(SAYAC);
    END LOOP;
END;
*/
/*
DECLARE 
    FAKTORIYEL NUMBER := 1;
BEGIN
    FOR SAYAC IN 1..5 LOOP
        FAKTORIYEL := FAKTORIYEL * SAYAC;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(FAKTORIYEL);
END;
*/

