DECLARE
   SICAKLIK NUMBER(3) := 25;
   CIKTI VARCHAR(300);
BEGIN
   CASE
        WHEN SICAKLIK>40 THEN CIKTI:=SICAKLIK||' DERECE HAVA ÇOK SICAK YÜZMEYE GÝT';
        WHEN SICAKLIK>25 THEN CIKTI:=SICAKLIK||' DERECE HAVA ILIMAN SÝNEMAYA GÝT';
        WHEN SICAKLIK=25 THEN CIKTI:=SICAKLIK||' DERECE HAVA ÇOK GÜZEL YÜRÜYÜÞE ÇIK';
        WHEN SICAKLIK>40 THEN CIKTI:=SICAKLIK||' DERECE HAVA BÝRAZ SOÐUK KAHVE ÝÇMEYE GÝT';
        ELSE                  CIKTI:=SICAKLIK||' DERECE HAVA ÇOK SOÐUK EVDE OTUR';
    
   END CASE;
   DBMS_OUTPUT.PUT_LINE(CIKTI);
END;
SET SERVEROUTPUT ON;