DECLARE 
    SAYI NUMBER :=&SAYI;
    CIKTI VARCHAR(300);
BEGIN
    CASE MOD(SAYI,2)
        WHEN 1 THEN CIKTI:='SAYI TEKTÝR';
        ELSE        CIKTI:='SAYI ÇÝFTTÝR';
    END CASE;
    DBMS_OUTPUT.PUT_LINE(CIKTI);
END;
