DECLARE
WÝMLEC SYS_REFCURSOR;
WQUERY VARCHAR2(1000);
WHASTA_NO HASTA2.HASTA_NO%TYPE;
WAD HASTA2.SOYAD%TYPE;
BEGIN
    WQUERY:='SELECT HASTA_NO,AD FROM HASTA2 WHERE HASTA_NO =1';
    OPEN WÝMLEC FOR WQUERY;

    LOOP
        FETCH WÝMLEC INTO WHASTA_NO,WAD;
        EXIT WHEN WÝMLEC%NOTFOUND ;
        DBMS_OUTPUT.PUT_LINE('WHASTA_NO'|| 'NUMARALI HASTA '||WAD);
    END LOOP;
    
    CLOSE WÝMLEC;
END;
